<!DOCTYPE html>
<html lang="pt-BR">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>Sistema Jurídico Próprio - Proposta</title>
  <style>
    @import url('https://fonts.googleapis.com/css2?family=Cormorant+Garamond:wght@600;700&family=Manrope:wght@400;500;600;700;800&display=swap');
    :root{--primary:#4b1e28;--secondary:#2f1118;--bg:#f7f1ea;--surface:#fffdfa;--surface-alt:#f1e8df;--surface-strong:#e2d3c2;--text:#1c1718;--text-body:#4f4346;--muted:#7f6f72;--border:#d8c8b7;--accent:#c6a76a;--accent-light:#eadfcb;--accent-soft:#b89452;--highlight:#dfc189;--success:#6f8a62;--success-light:#e2eadc;--warning:#b78943;--warning-light:#f3e6d2;--danger:#8b4a52;--danger-light:#f1dfe1;--shadow:0 8px 24px rgba(45,17,24,.08);--shadow-lg:0 18px 42px rgba(45,17,24,.14)}
    *{box-sizing:border-box;margin:0;padding:0} html{scroll-behavior:smooth}
    body{font-family:'Manrope',sans-serif;background:radial-gradient(circle at top left,rgba(198,167,106,.12),transparent 26%),radial-gradient(circle at right 20%,rgba(75,30,40,.08),transparent 24%),var(--bg);color:var(--text);line-height:1.75;font-size:17px;-webkit-font-smoothing:antialiased}
    h1,h2,h3,h4{font-family:'Cormorant Garamond',serif;color:var(--primary);font-weight:600;letter-spacing:.01em}
    .page{max-width:1100px;margin:0 auto 24px;padding:48px 56px;background:var(--surface);border:1px solid rgba(184,148,82,.18);border-radius:8px;box-shadow:var(--shadow)} .page--alt{background:var(--surface-alt)} .page--last{margin-bottom:0}
    .capa{min-height:640px;display:flex;flex-direction:column;justify-content:center;align-items:center;text-align:center;padding:64px;position:relative;overflow:hidden}.capa::before{content:"";position:absolute;inset:0;background:radial-gradient(circle at top,rgba(198,167,106,.16),transparent 42%)}
    .capa__eyebrow,.kicker{font:800 11px 'Manrope',sans-serif;letter-spacing:.18em;text-transform:uppercase;color:var(--accent-soft)} .capa__eyebrow{position:relative;z-index:1;margin-bottom:18px}
    .capa__logo{position:relative;z-index:1;width:100px;height:100px;border-radius:20px;overflow:hidden;border:1px solid var(--border);box-shadow:var(--shadow-lg);margin-bottom:28px;background:var(--surface)} .capa__logo img{width:100%;height:100%;object-fit:cover;display:block}
    .capa__title{position:relative;z-index:1;font-size:56px;line-height:1;margin-bottom:16px}.capa__subtitle{position:relative;z-index:1;max-width:720px;font-size:22px;line-height:1.55;color:var(--text-body);margin-bottom:28px}
    .capa__tagline{position:relative;z-index:1;padding:12px 24px;border-radius:999px;background:linear-gradient(180deg,rgba(234,223,203,.8),rgba(241,232,223,.96));font:800 12px 'Manrope',sans-serif;letter-spacing:.14em;text-transform:uppercase;color:var(--primary)}
    .grid-3,.resumo__grid,.modulo__help,.fechamento__decision-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:16px}.grid-4,.resumo__module-list,.fechamento__escopo{display:grid;grid-template-columns:repeat(4,1fr);gap:16px}
    .capa__stakes{position:relative;z-index:1;width:100%;max-width:820px;display:grid;grid-template-columns:repeat(3,1fr);gap:16px;margin-top:28px}.capa__stakes-item,.resumo__card,.fechamento__escopo-card{padding:20px;background:rgba(255,253,250,.84);border:1px solid rgba(198,167,106,.28);border-radius:14px;box-shadow:var(--shadow)} .capa__stakes-label,.resumo__card-num,.modulo__help-label{margin-bottom:8px;font:800 10px 'Manrope',sans-serif;letter-spacing:.14em;text-transform:uppercase;color:var(--accent-soft)} .capa__stakes-item p,.resumo__card p,.fechamento__escopo-card p{font-size:14px;color:var(--text-body);line-height:1.65}
    .resumo__header{margin-bottom:32px}.resumo__header h2,.fechamento__header h2{font-size:40px;margin-bottom:8px}.resumo__header p,.fechamento__header p{font-size:18px;color:var(--text-body)} .resumo__card h3,.fechamento__escopo-card h3{font-size:26px;margin-bottom:8px}
    .resumo__modules,.resumo__impact,.fechamento__decision{padding:28px;border-radius:18px;background:linear-gradient(135deg,rgba(75,30,40,.98),rgba(47,17,24,.98));box-shadow:var(--shadow-lg);color:#fff}.resumo__modules{margin-top:28px}.resumo__modules h3,.resumo__impact .kicker,.fechamento__decision .kicker{margin-bottom:12px;color:rgba(255,255,255,.68)}
    .resumo__module-item{display:flex;gap:10px;align-items:flex-start;font-size:14px;line-height:1.6}.resumo__module-item span{width:24px;height:24px;flex-shrink:0;border-radius:8px;display:flex;align-items:center;justify-content:center;background:rgba(255,255,255,.12);font:800 11px 'Manrope',sans-serif}
    .resumo__impact{margin-top:24px}.resumo__impact-quote,.fechamento__decision h3{font-size:32px;line-height:1.18;margin-bottom:14px;color:#fff}.resumo__impact p,.fechamento__decision p,.fechamento__decision-card span{font-size:15px;line-height:1.7;color:rgba(255,255,255,.84)}
    .modulo__header{display:flex;align-items:center;gap:16px;margin-bottom:24px}.modulo__badge{padding:8px 16px;border-radius:999px;background:var(--primary);color:#fff;font:800 11px 'Manrope',sans-serif;letter-spacing:.14em;text-transform:uppercase}.modulo__title{font-size:38px}
    .modulo__intro{margin-bottom:28px}.modulo__intro-title{font-size:28px;line-height:1.16;margin-bottom:8px}.modulo__intro p{font-size:15px;color:var(--text-body)} .modulo__pressure{margin-top:16px;padding:18px 20px;border-left:3px solid var(--danger);border-radius:12px;background:rgba(139,74,82,.08)} .modulo__pressure strong{display:block;margin-bottom:6px;font:800 10px 'Manrope',sans-serif;letter-spacing:.14em;text-transform:uppercase;color:var(--danger)} .modulo__pressure p{margin:0;font-size:14px;color:var(--text)}
    .submodulo{display:grid;grid-template-columns:1fr 1fr;gap:24px;margin-bottom:24px;padding:24px;background:rgba(255,253,250,.7);border:1px solid var(--border);border-radius:16px}.submodulo__header{display:flex;gap:12px;align-items:center;margin-bottom:14px} .submodulo__num{width:30px;height:30px;border-radius:9px;display:flex;align-items:center;justify-content:center;background:var(--primary);color:#fff;font:800 11px 'Manrope',sans-serif}
    .submodulo__title{font-size:24px;line-height:1.18}.submodulo__text p{margin-bottom:12px;font-size:15px;color:var(--text-body)} .submodulo__value{display:flex;flex-wrap:wrap;gap:8px;margin-bottom:14px}.submodulo__chip{padding:7px 10px;border-radius:999px;background:rgba(255,253,250,.95);border:1px solid rgba(198,167,106,.32);font:800 10px 'Manrope',sans-serif;letter-spacing:.08em;text-transform:uppercase;color:var(--primary)}
    .submodulo__features{list-style:none;display:flex;flex-direction:column;gap:8px}.submodulo__features li{display:flex;gap:8px;align-items:flex-start;font-size:14px;color:var(--text-body);line-height:1.6}.submodulo__features li::before{content:"+";color:var(--accent-soft);font-weight:800}
    .mockup{padding:16px;background:var(--surface);border:1px solid var(--border);border-radius:14px;box-shadow:var(--shadow)} .mockup__header{display:flex;gap:8px;align-items:center;margin-bottom:12px;padding-bottom:10px;border-bottom:1px solid var(--surface-strong)} .mockup__dot{width:8px;height:8px;border-radius:50%;background:var(--border)} .mockup__dot--red{background:#e8a5a5}.mockup__dot--yellow{background:#e8d5a5}.mockup__dot--green{background:#a5e8b5}
    .mockup__content{display:flex;gap:12px}.mockup__sidebar{width:96px;flex-shrink:0;padding:8px;border-radius:8px;background:var(--surface-alt)} .mockup__nav-item{margin-bottom:4px;padding:6px 8px;border-radius:5px;font-size:10px;color:var(--text-body)} .mockup__nav-item--active{background:var(--primary);color:#fff}
    .mockup__main{flex:1;display:flex;flex-direction:column;gap:8px}.mockup__card{padding:10px;border:1px solid var(--border);border-radius:8px;background:var(--surface-alt)} .mockup__card-header{display:flex;justify-content:space-between;align-items:center;gap:8px;margin-bottom:6px} .mockup__card-title{font:800 11px 'Manrope',sans-serif;color:var(--text)}
    .mockup__badge{padding:2px 6px;border-radius:999px;font:800 9px 'Manrope',sans-serif;letter-spacing:.08em;text-transform:uppercase}.mockup__badge--success{background:var(--success-light);color:var(--success)}.mockup__badge--warning{background:var(--warning-light);color:var(--warning)}.mockup__badge--danger{background:var(--danger-light);color:var(--danger)}.mockup__badge--info{background:var(--accent-light);color:var(--primary)}
    .mockup__card-body{font-size:10px;color:var(--text-body);line-height:1.5}.mockup__card-row{display:flex;justify-content:space-between;gap:8px;margin-bottom:4px}.mockup__card-row:last-child{margin-bottom:0}
    .mockup__signal,.mockup__callout{padding:10px;border-radius:8px;font-size:10px;line-height:1.55}.mockup__signal{background:var(--accent-light);color:var(--primary);font-weight:800}.mockup__signal--success{background:var(--success-light);color:var(--success)}.mockup__signal--danger{background:var(--danger-light);color:var(--danger)} .mockup__callout{border:1px dashed rgba(198,167,106,.42);background:rgba(234,223,203,.35);color:var(--text-body)}
    .mockup--kanban .mockup__content{display:grid;grid-template-columns:repeat(3,1fr);gap:8px}.mockup__column{padding:8px;border-radius:8px;background:var(--surface-alt)} .mockup__column-header{margin-bottom:8px;padding-bottom:6px;border-bottom:1px solid var(--border);font:800 9px 'Manrope',sans-serif;letter-spacing:.08em;text-transform:uppercase;color:var(--muted)}
    .mockup__task{margin-bottom:6px;padding:6px;border-radius:5px;border:1px solid var(--border);background:var(--surface);font-size:9px}.mockup__task:last-child{margin-bottom:0}.mockup__task-title{margin-bottom:4px;font-weight:700;color:var(--text)} .mockup__task-meta{display:flex;justify-content:space-between;align-items:center}.mockup__task-avatar{width:14px;height:14px;border-radius:50%;display:flex;align-items:center;justify-content:center;background:var(--accent);color:#fff;font-size:6px;font-weight:800}
    .mockup__task-priority{width:5px;height:5px;border-radius:50%}.mockup__task-priority--high{background:var(--danger)}.mockup__task-priority--medium{background:var(--warning)}.mockup__task-priority--low{background:var(--success)}
    .mockup__docs,.mockup__notif-list{display:flex;flex-direction:column;gap:6px}.mockup__doc,.mockup__notif{display:flex;gap:8px;align-items:flex-start;padding:8px;border-radius:8px;background:var(--surface-alt)} .mockup__doc-icon{width:22px;height:22px;border-radius:6px;display:flex;align-items:center;justify-content:center;font:800 9px 'Manrope',sans-serif} .mockup__doc-icon--pdf{background:#fce4e4;color:#c53030}.mockup__doc-icon--img,.mockup__doc-icon--doc{background:#e4f0fc;color:#2b6cb0}
    .mockup__doc-info{flex:1}.mockup__doc-name,.mockup__notif-title{font-size:10px;font-weight:700;color:var(--text)} .mockup__doc-meta,.mockup__notif-text{font-size:9px;color:var(--muted)} .mockup__doc-status{width:7px;height:7px;border-radius:50%;background:var(--success)} .mockup__doc-status--pending{background:var(--warning)}
    .mockup__timeline{display:flex;gap:6px;padding-top:8px;border-top:1px solid var(--border)} .mockup__timeline-item{flex:1;text-align:center}.mockup__timeline-dot{width:6px;height:6px;margin:0 auto 4px;border-radius:50%;background:var(--border)} .mockup__timeline-dot--active{background:var(--success)} .mockup__timeline-dot--current{background:var(--warning)} .mockup__timeline-label{font-size:8px;color:var(--muted)}
    .mockup--search .mockup__content{flex-direction:column;gap:10px}.mockup__search-bar{display:flex;gap:8px;align-items:center;padding:8px 10px;border:1px solid var(--border);border-radius:8px;background:var(--surface-alt)} .mockup__search-bar input{width:100%;border:none;background:transparent;color:var(--text);font-size:11px}.mockup__search-filters{display:flex;gap:6px;flex-wrap:wrap}.mockup__filter{padding:3px 8px;border-radius:999px;border:1px solid var(--border);background:var(--surface);font-size:9px;color:var(--text-body)} .mockup__filter--active{background:var(--primary);border-color:var(--primary);color:#fff}
    .mockup__notif{border-left:2px solid var(--accent)} .mockup__notif-icon{width:18px;height:18px;flex-shrink:0;border-radius:5px;display:flex;align-items:center;justify-content:center;background:var(--accent-light);color:var(--primary);font-size:11px} .mockup__notif-time{font-size:8px;color:var(--muted);margin-top:2px}
    .mockup__table{width:100%;border-collapse:collapse;font-size:10px}.mockup__table th{padding:6px 8px;text-align:left;border-bottom:1px solid var(--border);background:var(--surface-alt);color:var(--text-body);font:800 9px 'Manrope',sans-serif;letter-spacing:.08em;text-transform:uppercase}.mockup__table td{padding:6px 8px;border-bottom:1px solid var(--surface-strong);color:var(--text-body)} .mockup__table tr:last-child td{border-bottom:none}
    .mockup__avatar-group{display:flex}.mockup__avatar{width:20px;height:20px;margin-left:-6px;border-radius:50%;border:2px solid var(--surface);display:flex;align-items:center;justify-content:center;color:#fff;font:800 8px 'Manrope',sans-serif}.mockup__avatar:first-child{margin-left:0}
    .modulo__help{margin-top:26px;padding:20px;border-radius:14px;border-left:3px solid var(--accent-soft);background:linear-gradient(180deg,rgba(234,223,203,.64),rgba(241,232,223,.95))}.modulo__help p{font-size:14px;color:var(--primary);line-height:1.55}
    .fechamento__decision-grid{margin-top:18px}.fechamento__decision-card{padding:18px;border-radius:14px;background:rgba(255,255,255,.08);border:1px solid rgba(255,255,255,.12)} .fechamento__decision-card strong{display:block;margin-bottom:8px;font:800 10px 'Manrope',sans-serif;letter-spacing:.14em;text-transform:uppercase;color:var(--highlight)}
    .fechamento__header{text-align:center;margin-bottom:30px}.fechamento__escopo-card{text-align:center}.fechamento__prox{padding:28px;border-radius:16px;background:rgba(255,253,250,.8);border:1px solid var(--border);text-align:center}.fechamento__prox h3{font-size:30px;margin-bottom:8px}.fechamento__prox p{font-size:15px;color:var(--text-body);line-height:1.7}
    .page-footer{padding-top:22px;margin-top:10px;border-top:1px solid var(--border);display:flex;justify-content:space-between;align-items:center;font-size:12px;color:var(--muted)} .page-footer__brand{font-weight:700;color:var(--text-body)}
    @media (max-width:900px){.page{padding:32px}.capa{padding:40px 32px}.capa__title{font-size:42px}.capa__subtitle,.resumo__impact-quote,.fechamento__decision h3{font-size:28px}.capa__stakes,.resumo__grid,.resumo__module-list,.submodulo,.modulo__help,.fechamento__decision-grid,.fechamento__escopo,.mockup--kanban .mockup__content{grid-template-columns:1fr}.mockup__content,.modulo__header,.page-footer{flex-direction:column}.mockup__sidebar{width:100%}.modulo__header,.page-footer{align-items:flex-start}}
    @media print{body{background:#fff}.page{margin:0;max-width:100%;box-shadow:none}}
  </style>
</head>
<body>
<?php
$modules = glob('modules/*.html');
natsort($modules);
foreach ($modules as $module) {
    include $module;
}
?>
</body>
</html>
